---
#
# Ansible Playbook to install ELK stack on Ubuntu
#
- hosts: elkservers
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  #- { role: metricbeat }
  #- { role: filebeat }
  #- { role: x-pack}

