---
#
# Ansible Playbook to install ELK stack on RHEL
#
- name: Install ELhosts: elkservers
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  #- { role: logstash }
  #- { role: metricbeat }
  #- { role: filebeat }


