---
#
# Installing Java 8 for Elasticsearch
#

# Add the Java repo

#- name: Add the Java EPEL repo
#  yum_repository: 
#   name: Java
#   description: EPEL YUM repo
#   baseurl: http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jre-8u171-linux-x64.rpm

  
# Install Java 

- name: Download Java
  command: "curl -Lo jre-8-linux-x64.rpm --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jre-8u171-linux-x64.rpm"
  warn: no

- name: Install Java 8
  yum:
   name: jre-8-linux-x64.rpm
   state: present
   update_cache: yes
