---
#
# Installing Elasticsearch 6.x with RPM
#

# Add Elasticsearch rpm key

- name: Add Elasticsearch rpm key
  rpm_key:
   state: present
   key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

# Add the ELK apt repo for version 6.x

- name: Adding Elasticsearch repo
  yum_repository:
   name: elasticsearch
   description: elasticsearch yum repo
   baseurl: https://artifacts.elastic.co/packages/6.x/yum
   gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   gpgcheck: yes
   enabled: yes

# Installing Elasticsearch

- name: Install Elasticsearch
  yum:
   name: elasticsearch-6.2.4
   update_cache: yes
   
# Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost'). 

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 0.0.0.0'
 
# Update Elasticsearch port in config file 

- name: Updating the port in config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'
 
# Start Elasticsearch
- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: started
    
